#ifndef ASYNCSERIALINTERFACE_GLOBAL_H
#define ASYNCSERIALINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASYNCSERIALINTERFACE_LIBRARY)
#  define ASYNCSERIALINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define ASYNCSERIALINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // ASYNCSERIALINTERFACE_GLOBAL_H
