#ifndef SERIALCARDREADER_GLOBAL_H
#define SERIALCARDREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALCARDREADER_LIBRARY)
#  define SERIALCARDREADER_EXPORT Q_DECL_EXPORT
#else
#  define SERIALCARDREADER_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALCARDREADER_GLOBAL_H
